### ISSUE TITLE
Changes in the Project's API

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [sociomantic-tsunami/octod#26]
There are some breaking changes coming to the Project API, we should check if anything needs adapting.

https://developer.github.com/changes/2017-09-01-breaking-changes-to-projects-api-preview-and-webhooks-date-format/

**Comment by mihails-strasuns-sociomantic** [comment]
No, we don't interact with project create/update dates and AFAICS this is the only breaking change mentioned.
