### ISSUE TITLE
Generate and publish DDOC

### ISSUE THREAD

**Issue by mihails-strasuns-sociomantic** [sociomantic-tsunami/octod#6]
Simply pushing generated HTML to gh-pages should be sufficient for initial release

**Comment by mihails-strasuns-sociomantic** [comment]
@leandro-lucarella-sociomantic @nemanja-boric-sociomantic using harbored for that would be nice but it will probably take too long time, right?

**Comment by leandro-lucarella-sociomantic** [comment]
I think nemanja wrote some patches for harbored-mod that weren't accepted yet, otherwise we could just build it as part of the testing, similarly to what we want to do with ocean and tango.

**Comment by nemanja-boric-sociomantic** [comment]
Yeah, I think that's the best way to proceed.

**Comment by nemanja-boric-sociomantic** [comment]
Yeah, unless the patches are accepted, we just do simple `sed` on `dub.json` as part of the docker image build. There are also some other patches, but they are just enhancements, and not really needed for the base functionally.

**Comment by leandro-lucarella-sociomantic** [comment]
Closing as this repo will be archived.
